=== DataBrewery/cubes/cubes/schemas/model.json
{
    "$schema": "http://json-schema.org/schema",
    "title": "Cubes Model",
    "type": "object",

    "properties": {
        "name": {"type": "string"},
        "label": {"type": "string"},
        "description": {"type": "string"},
        "info": {"type": "object"},

        "provider": {"type": "string"},

        "browser_options": {"type": "object"},

        "cubes": {"type": "array"},
        "dimensions": {"type": "array"},

        "schema": {"type": "string"},
        "store": {"type": "string"},
        "mappings": {"type": "object"},
        "joins": {"type": "array"}
    },
    "additionalProperties": false
}

=== DataBrewery/cubes/tests/resources/models/test.cubesmodel/cube_contracts.json
{
	"name": "contracts",
	"label": "Uzatvorené zmluvy verejného obstarávania",
	"description": "Uzatvorené zmluvy verejného obstarávania Slovenskej Republiky",

	"dimensions": [ "date",
					"cpv",
					"procurer",
					"supplier",
					"process_type",
					"geography"],
	"joins": [
		{
			"master": "zmluvy.vestnik_datum_id",
			"detail": "date.id"
		},
		{
			"master": "zmluvy.cpv_kod_id",
			"detail": "cpv.id"
		},
		{
			"master": "zmluvy.obstaravatel_org_id",
			"detail": "obstaravatel.id"
		},
		{
			"master": "zmluvy.dodavatel_id",
			"detail": "dodavatel.id"
		},
		{
			"master": "zmluvy.druh_postupu_id",
			"detail": "druh_postupu.id"
		},
		{
			"master": "zmluvy.kriteria_vyhodnotenia_id",
			"detail": "kriteria_vyhodnotenia.id"
		},
		{
			"master": "zmluvy.geography_id",
			"detail": "geography.id"
		}
	],
	"mappings": {
	    "date.year": "dim_date.year",
	    "date.month": "dim_date.month",
	    "date.day": "dim_date.day",
	    "cpv.group": "dim_cpv.cpv_group",
	    "cpv.class": "dim_cpv.cpv_class"
	}
}
